--------------------------------------------------------
--  File created - Cleanup Script
--  Removes all Tables and Sequences for HOMESTAY schema
--------------------------------------------------------

-- Drop Sequences
DROP SEQUENCE "HOMESTAY"."BILL_SEQ";
DROP SEQUENCE "HOMESTAY"."BOOKING_SEQ";
DROP SEQUENCE "HOMESTAY"."GUEST_SEQ";
DROP SEQUENCE "HOMESTAY"."HOMESTAY_SEQ";
DROP SEQUENCE "HOMESTAY"."MEMBERSHIP_SEQ";
DROP SEQUENCE "HOMESTAY"."SERVICE_SEQ";
DROP SEQUENCE "HOMESTAY"."STAFF_SEQ";

-- Drop Tables 
DROP TABLE "HOMESTAY"."HOMESTAY_SERVICE" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."BOOKING" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."BILL" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."MEMBERSHIP" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."FULL_TIME" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."PART_TIME" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."SERVICE" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."HOMESTAY" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."GUEST" CASCADE CONSTRAINTS;
DROP TABLE "HOMESTAY"."STAFF" CASCADE CONSTRAINTS;

COMMIT;
